questions = [
    {
        "id": "ts1_short_01",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "easy",
        "question": "What is the primary purpose of Directive 2006/54/EC?",
        "answer": "",
        "ground_truth": "The purpose of the Directive is to ensure the implementation of the principle of equal opportunities and equal treatment of men and women in matters of employment and occupation.[cite: 1]",
        "article_refs": ["Article 1"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_02",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "easy",
        "question": "How is 'direct discrimination' defined in the context of this Directive?",
        "answer": "",
        "ground_truth": "Direct discrimination occurs where one person is treated less favourably on grounds of sex than another is, has been, or would be treated in a comparable situation.[cite: 1]",
        "article_refs": ["Article 2(1)(a)"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_03",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "medium",
        "question": "Does harassment and sexual harassment constitute discrimination under this Directive?",
        "answer": "",
        "ground_truth": "Yes, harassment and sexual harassment are contrary to the principle of equal treatment and constitute discrimination on grounds of sex for the purposes of the Directive.[cite: 1]",
        "article_refs": ["Recital 6", "Article 2(2)(a)"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_04",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "medium",
        "question": "What requirement is placed on job classification systems used for determining pay?",
        "answer": "",
        "ground_truth": "Job classification systems must be based on the same criteria for both men and women and drawn up so as to exclude any discrimination on grounds of sex.[cite: 1]",
        "article_refs": ["Article 4"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_05",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "easy",
        "question": "What rights does a woman have regarding her post after returning from maternity leave?",
        "answer": "",
        "ground_truth": "A woman is entitled to return to her job or an equivalent post on terms no less favourable and to benefit from any improvement in working conditions she would have been entitled to during her absence.[cite: 1]",
        "article_refs": ["Article 15"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_06",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "hard",
        "question": "In a prima facie case of discrimination, who carries the burden of proof in judicial procedures?",
        "answer": "",
        "ground_truth": "Once a plaintiff establishes facts from which it may be presumed there has been discrimination, it is for the respondent to prove that there has been no breach of the principle of equal treatment.[cite: 1]",
        "article_refs": ["Article 19(1)"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_07",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "hard",
        "question": "Name one type of contract or scheme excluded from the material scope of Chapter 2 regarding social security.",
        "answer": "",
        "ground_truth": "Exclusions include individual contracts for self-employed persons, single-member schemes for self-employed persons, or insurance contracts to which the employer is not a party.[cite: 1]",
        "article_refs": ["Article 8(1)"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_08",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "medium",
        "question": "Can an employer dismiss an employee for testifying in a discrimination case involving another worker?",
        "answer": "",
        "ground_truth": "No. Member States must introduce measures to protect employees against dismissal or adverse treatment as a reaction to legal proceedings aimed at enforcing compliance.[cite: 1]",
        "article_refs": ["Article 24"],
        "contexts": [],
        "adversarial": True
    },
    {
        "id": "ts1_short_09",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "medium",
        "question": "What is one required competence of the national 'equality bodies' designated by Member States?",
        "answer": "",
        "ground_truth": "Competences include providing independent assistance to victims, conducting independent surveys, or publishing independent reports and recommendations on discrimination.[cite: 1]",
        "article_refs": ["Article 20(2)"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_10",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "easy",
        "question": "According to the definitions, does 'pay' include considerations in kind?",
        "answer": "",
        "ground_truth": "Yes, 'pay' includes the ordinary basic or minimum wage and any other consideration, whether in cash or in kind, received directly or indirectly from the employer.[cite: 1]",
        "article_refs": ["Article 2(1)(e)"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_short_11",
        "test_set": 1,
        "answer_type": "short",
        "difficulty": "medium",
        "question": "What was the general deadline for Member States to bring into force the laws necessary to comply with this Directive?",
        "answer": "",
        "ground_truth": "Member States were required to comply by 15 August 2008 at the latest, with a possible one-year extension for particular difficulties.[cite: 1]",
        "article_refs": ["Article 33"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_medium_01",
        "test_set": 1,
        "answer_type": "medium",
        "difficulty": "hard",
        "question": "Under what specific conditions may a difference in treatment based on a characteristic related to sex not constitute discrimination regarding access to employment?",
        "answer": "",
        "ground_truth": "A difference in treatment is permitted if, by reason of the nature of the occupational activities or the context they are carried out, the characteristic constitutes a genuine and determining occupational requirement. This is provided the objective is legitimate and the requirement is proportionate. Member States must periodically assess these exclusions.[cite: 1]",
        "article_refs": ["Article 14(2)", "Article 31(3)"],
        "contexts": [],
        "adversarial": False
    },
    {
        "id": "ts1_long_01",
        "test_set": 1,
        "answer_type": "long",
        "difficulty": "hard",
        "question": "Outline the material scope of equal treatment in occupational social security schemes and provide at least four examples of provisions that would be considered discriminatory under Article 9.",
        "answer": "",
        "ground_truth": "The Directive applies to schemes providing protection against sickness, invalidity, old age, industrial accidents, occupational diseases, and unemployment, as well as those providing other social benefits like survivors' benefits if they constitute consideration paid by the employer. Discriminatory provisions under Article 9 include: (1) determining participation based on sex; (2) fixing different retirement ages; (3) setting different levels of benefit (subject to certain actuarial exceptions); (4) fixing different entry ages or membership periods; and (5) suspending rights during maternity leave paid by the employer.[cite: 1]",
        "article_refs": ["Article 7", "Article 9"],
        "contexts": [],
        "adversarial": True
    }
]