questions = [
    {"id": "ts1_short_01", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "Qual è lo scopo principale della direttiva 2006/54/CE?", "answer": "", "ground_truth": "Garantire l’attuazione del principio di pari opportunità e parità di trattamento tra uomini e donne in materia di occupazione e impiego.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_02", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "Come viene definita la discriminazione diretta nella direttiva?", "answer": "", "ground_truth": "È il trattamento meno favorevole di una persona rispetto a un’altra in situazione analoga basato sul sesso.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_03", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "Le molestie rientrano nel concetto di discriminazione?", "answer": "", "ground_truth": "Sì, le molestie e le molestie sessuali sono considerate forme di discriminazione fondate sul sesso.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_04", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "La direttiva si applica anche al settore privato?", "answer": "", "ground_truth": "Sì, si applica sia al settore pubblico che a quello privato.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_05", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "La gravidanza è tutelata come causa di discriminazione?", "answer": "", "ground_truth": "Sì, ogni trattamento sfavorevole legato alla gravidanza costituisce discriminazione diretta.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_06", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "La parità di trattamento riguarda anche la retribuzione?", "answer": "", "ground_truth": "Sì, la retribuzione rientra pienamente nel principio di parità di trattamento.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_07", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "È ammesso il ricorso all’azione positiva?", "answer": "", "ground_truth": "Sì, per favorire il sesso sottorappresentato nella vita lavorativa.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_08", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "La direttiva tutela i lavoratori autonomi?", "answer": "", "ground_truth": "Sì, in relazione ai regimi professionali di sicurezza sociale.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_09", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "È previsto il diritto al rientro dopo il congedo di maternità?", "answer": "", "ground_truth": "Sì, è garantito il diritto a rientrare nello stesso lavoro o in uno equivalente.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_10", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "È vietata la vittimizzazione del lavoratore discriminato?", "answer": "", "ground_truth": "Sì, è vietato qualsiasi trattamento ritorsivo.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_short_11", "test_set": 1, "answer_type": "short", "difficulty": "easy", "question": "La direttiva vieta discriminazioni nei regimi professionali di sicurezza sociale?", "answer": "", "ground_truth": "Sì, vieta qualsiasi discriminazione fondata sul sesso in tali regimi.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_medium_01", "test_set": 1, "answer_type": "medium", "difficulty": "medium", "question": "In che modo la direttiva definisce e disciplina la discriminazione indiretta?", "answer": "", "ground_truth": "La discriminazione indiretta si verifica quando una disposizione apparentemente neutra pone persone di un sesso in particolare svantaggio rispetto all’altro, salvo che sia oggettivamente giustificata da una finalità legittima e perseguita con mezzi proporzionati.", "article_refs": [], "contexts": [], "adversarial": False},
    {"id": "ts1_long_01", "test_set": 1, "answer_type": "long", "difficulty": "hard", "question": "Spiega il principio della parità retributiva previsto dalla direttiva 2006/54/CE.", "answer": "", "ground_truth": "La direttiva stabilisce che uomini e donne devono ricevere la stessa retribuzione per uno stesso lavoro o per un lavoro di pari valore. Il valore del lavoro deve essere determinato sulla base di criteri oggettivi e neutrali rispetto al sesso, come competenze, responsabilità e condizioni di lavoro. Qualsiasi sistema di classificazione professionale deve essere costruito in modo da eliminare discriminazioni dirette e indirette.", "article_refs": [], "contexts": [], "adversarial": False}
]